version: '3.1'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  bot:
    image: ieatbot
    links:
      - db
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep bot.py | wc -l | tr 1 ' '"]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./token:/home/bot/token
    command:
      "/bin/bash /home/bot/entrypoint.sh"
