version: '3.1'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
  bot:
    image: ieatbot
    depends_on:
      - db
    volumes:
      - ./token:/home/bot/token
    command:
      "/bin/bash /home/bot/entrypoint.sh"
